GCC_FLAGS = -Wall -g
CC = gcc

all : exo1 exo2 exo3

mgrep1 : exo1.c
	${CC} ${GCC_FLAGS} -o $@ $^

mgrep2 : exo2.c
	${CC} ${GCC_FLAGS} -o $@ $^

mgrep3 : exo3.c
	${CC} ${GCC_FLAGS} -o $@ $^

clean : 
	rm *.o


